name: athletic
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^1.1.0
  flutter_screenutil: ^5.5.3+2
  expandable_page_view: ^1.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: edosz
      fonts:
        - asset: fonts/edosz.ttf
          style: normal
    - family: LexendBold
      fonts:
        - asset: fonts/Lexend-Bold.ttf
          style: normal
    - family: LexendExtraBold
      fonts:
        - asset: fonts/Lexend-ExtraBold.ttf
          style: normal
    - family: LexendLight
      fonts:
        - asset: fonts/Lexend-Light.ttf
          style: normal
    - family: LexendMedium
      fonts:
        - asset: fonts/Lexend-Medium.ttf
          style: normal
    - family: LexendRegular
      fonts:
        - asset: fonts/Lexend-Regular.ttf
          style: normal
    - family: LexendSemiBold
      fonts:
        - asset: fonts/Lexend-SemiBold.ttf
          style: normal
    - family: LexendThin
      fonts:
        - asset: fonts/Lexend-Thin.ttf
          style: normal